---
# defaults file for docker_host

docker_host_prerequisite_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python-pip
  - virtualenv

docker_host_version: stable

docker_host_repos:
  - deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial {{ docker_host_version }}

docker_host_python_modules:
  - { module: docker, version: 3.4.1 }

docker_host_user: docker-user
