---
galaxy_info:
  author: Aleksandr Loktionov
  description: none
  company: none

  license: BSD

  min_ansible_version: 2.7

  platforms:
    - name: Ubuntu
      versions:
        - xenial

  galaxy_tags:
    - ansible
    - awx
    - infrastructure

dependencies:
  - role: geerlingguy.ansible
    become: true
    tags:
      - awx_wrapper_install
      - install
  - role: geerlingguy.git
    become: true
    tags:
      - awx_wrapper_install
      - install
  - role: geerlingguy.docker
    become: true
    tags:
      - awx_wrapper_install
      - install
  - role: geerlingguy.pip
    become: true
    tags:
      - awx_wrapper_install
      - install
  - role: geerlingguy.nodejs
    become: true
    tags:
      - skip_ansible_lint
      - awx_wrapper_install
      - install
