---
# defaults file for gitlab

gitlab_hostname: "{{ inventory_hostname }}"
gitlab_domain: localdomain
gitlab_external_url: http://{{ gitlab_hostname }}.{{ gitlab_domain }}

gitlab_dir: /srv/gitlab
gitlab_config_dir: "{{ gitlab_dir }}/config"
gitlab_data_dir: "{{ gitlab_dir }}/data"
gitlab_log_dir: "{{ gitlab_dir }}/logs"

gitlab_docker_compose:
  version: '3'
  services:
    web:
      image: 'gitlab/gitlab-ce:latest'
      restart: always
      hostname: '{{ gitlab_hostname }}'
      healthcheck:
        test: ["CMD", "curl", "--fail", "http://localhost"]
        interval: 1m30s
        timeout: 10s
        retries: 3
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url '{{ gitlab_external_url }}'
      ports:
        - '80:80'
        - '443:443'
        - '2222:22'
      volumes:
        - '{{ gitlab_config_dir }}:/etc/gitlab'
        - '{{ gitlab_log_dir }}:/var/log/gitlab'
        - '{{ gitlab_data_dir }}:/var/opt/gitlab'
