---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: awx-wrapper-xenial
    box: ubuntu/xenial64
    memory: 2048
    cpus: 4
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 443, host: 13443"
      - "vm.network 'forwarded_port', guest: 80, host: 13080"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        docker_host_user: vagrant
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
