FROM alpine:3.7
ENV APP_HOME /app
RUN apk add g++ \
            make \
            ruby \
            ruby-dev && \
    mkdir -p $APP_HOME && \
    gem install bundler --no-ri --no-rdoc 

WORKDIR $APP_HOME
COPY . $APP_HOME
RUN bundle install

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
