FROM alpine:3.7 AS build
ENV APP_HOME /app
RUN apk add g++ \
            make \
            ruby \
            ruby-dev && \
    mkdir -p $APP_HOME && \
    gem install bundler --no-ri --no-rdoc 

WORKDIR $APP_HOME
COPY . $APP_HOME
RUN bundle install --jobs 4 --deployment --binstubs --standalone

FROM alpine:3.7
ENV APP_HOME /app
RUN apk add --no-cache ruby
COPY --from=build $APP_HOME $APP_HOME
WORKDIR $APP_HOME
ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["/app/bin/puma"]
