source 'https://rubygems.org'

gem 'sinatra', '~> 2.0.1'
gem 'bson_ext'
gem 'mongo'
gem 'puma'
gem 'prometheus-client'
gem 'rack'
gem 'rufus-scheduler'
gem 'json'
# https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors
gem 'tzinfo-data'
