---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: reddit-monolith-xenial
    box: ubuntu/xenial64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 9292, host: 9292"
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        docker_host_user: vagrant
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
