version: '3.3'
services:
  prometheus:
    image: ${USER_NAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    networks:
      - front_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
  mongodb_exporter:
    image: loktionovam/mongodb_exporter:${MONGODB_EXPORTER_VERSION}
    environment:
      - MONGODB_URL='mongodb://comment_db:27017'
    networks:
      - front_net
      - back_net
  blackbox_exporter:
    image: loktionovam/blackbox_exporter:${BLACKBOX_EXPORTER_VERSION}
    networks:
      - front_net
      - back_net
  cadvisor:
    image: google/cadvisor:v${CADVISOR_VERSION}
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - front_net
  grafana:
    image: loktionovam/grafana:${GRAFANA_VERSION}
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - front_net
  alertmanager:
    image: ${USER_NAME}/alertmanager:${ALERTMANGER_VERSION}
    ports:
      - 9093:9093
    networks:
      - front_net
  telegraf:
    image: ${USER_NAME}/telegraf:${TELEGRAF_VERSION}
    ports:
      - 9273:9273
    networks:
      - front_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  stackdriver:
    image: loktionovam/stackdriver-exporter:${STRACKDRIVER_VERSION}
    ports:
      - 9255:9255
    networks:
      - front_net
    environment:
      - STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES="${STACKDRIVER_METRICS_PREFIXES}"
      - STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID=/stackdriver.secrets
      - GOOGLE_APPLICATION_CREDENTIALS=/gce-service-account.json
volumes:
  prometheus_data:
  grafana_data:
networks:
  back_net:
  front_net:
