{
 "title": "Docker container performance monitoring",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Container CPU Usage (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers memory (RSS)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "docker_container_mem_rss", "legendFormat": "{{ container_name }}" }
   ]
  },
  {
   "title": "Containers disk kilobytes read rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_read{device=\"253:0\"}[5m])/1024",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers disk kilobytes write rate",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_write{device=\"253:0\"}[5m])/1024",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers network kilobytes per second (RX)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes[1m])/1024",
     "legendFormat": "{{ container_name  }} - {{ network }}"
    }
   ]
  },
  {
   "title": "Containers network kilobytes per second (TX)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_tx_bytes[1m])/1024",
     "legendFormat": "{{ container_name  }} - {{ network }}"
    }
   ]
  }
 ]
}