{
 "title": "GCP stackdriver",
 "time": { "from": "2018-10-07T10:51:54.847Z", "to": "2018-10-07T11:35:30.472Z" },
 "panels": [
  {
   "title": "Docket host sent/receive network packets (1 min interval)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Sent/receive network packets" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_network_sent_packets_count",
     "legendFormat": "{{instance_name}} sent packets"
    },
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_network_received_packets_count",
     "legendFormat": "{{instance_name}} receive packets"
    }
   ]
  },
  {
   "title": "Docker host network receive/sent bytes (1 min interval)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Receive/sent bytes" }
   ],
   "targets": [
    {
     "expr": "ratestackdriver_gce_instance_compute_googleapis_com_instance_network_received_bytes_count",
     "legendFormat": "{{instance_name}} receive"
    },
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_network_sent_bytes_count",
     "legendFormat": "{{instance_name}} sent"
    }
   ]
  },
  {
   "title": "Docker host disk read write I/O (1 min interval)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "IO per second" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_disk_write_ops_count{device_name=~\"docker-host.*\"}",
     "legendFormat": "{{instance_name}} write ops"
    },
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_disk_read_ops_count{device_name=~\"docker-host.*\"}",
     "legendFormat": "{{instance_name}} read ops"
    }
   ]
  },
  {
   "title": "GCE instance CPU utilization (1 min interval)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_cpu_utilization",
     "legendFormat": "{{instance_name }} load"
    }
   ]
  }
 ]
}