- name: Copy the appropriate certificates and private keys to each worker instance
  hosts: tag_worker

  vars:
    gce_project: "{{ lookup('env','GCE_PROJECT') }}"
    gce_region: "{{ lookup('env','GCE_REGION') }}"
    gce_credentials_file: "{{ lookup('env','GCE_CREDENTIALS') }}"

  tasks:

    - name: Copy the appropriate certificates and private keys to each worker instance
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      with_items:
        - ca.pem
        - "{{ inventory_hostname }}-key.pem"
        - "{{ inventory_hostname }}.pem"
      no_log: true
