- name: Copy the appropriate certificates and private keys to each controller instance
  hosts: tag_controller

  vars:
    gce_project: "{{ lookup('env','GCE_PROJECT') }}"
    gce_region: "{{ lookup('env','GCE_REGION') }}"
    gce_credentials_file: "{{ lookup('env','GCE_CREDENTIALS') }}"

  tasks:

    - name: Copy the appropriate certificates and private keys to each controller instance
      copy:
        src: "{{ item }}"
        dest: "{{ item }}"
      with_items:
        - ca.pem
        - ca-key.pem
        - kubernetes-key.pem
        - kubernetes.pem
        - service-account-key.pem
        - service-account.pem
      no_log: true
