---

- name: Check if {{ item }} kubeconfig exists
  stat:
    path: files/{{ item }}.kubeconfig
  register: kubeconfig

- name: Generate a kubeconfig file for the {{ item }} service
  block:
    - name: Set {{ item }} cluster in kubeconfig
      command: |
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://127.0.0.1:6443 \
        --kubeconfig={{ item }}.kubeconfig
      args:
        chdir: files

    - name: Set {{ item }} credentials in kubeconfig
      command: |
        kubectl config set-credentials system:{{ item }} \
        --client-certificate={{ item }}.pem \
        --client-key={{ item }}-key.pem \
        --embed-certs=true \
        --kubeconfig={{ item }}.kubeconfig
      args:
        chdir: files

    - name: Set {{ item }} context in kubeconfig
      command: |
        kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:{{ item }} \
        --kubeconfig={{ item }}.kubeconfig
      args:
        chdir: files

    - name: Set {{ item }} use context in kubeconfig
      command: kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
      args:
        chdir: files

  when: kubeconfig.stat.exists == false
