---

- name: Check if worker-{{ item }} kubeconfig exists
  stat:
    path: files/worker-{{ item }}.kubeconfig
  register: worker_kubeconfig

- name: Generate worker-{{ item }} kubeconfig
  block:
    - name: Set worker-{{ item }} cluster in kubeconfig
      command: |
        kubectl config set-cluster kubernetes-the-hard-way \
        --certificate-authority=ca.pem \
        --embed-certs=true \
        --server=https://{{ kubernetes_public_ip['items'].0.address }}:6443 \
        --kubeconfig=${instance}.kubeconfig
      args:
        chdir: files

    - name: Set worker-{{ item }} credentials in kubeconfig
      command: |
        kubectl config set-credentials system:node:worker-{{ item }} \
        --client-certificate=worker-{{ item }}.pem \
        --client-key=worker-{{ item }}-key.pem \
        --embed-certs=true \
        --kubeconfig=worker-{{ item }}.kubeconfig
      args:
        chdir: files

    - name: Set worker-{{ item }} context in kubeconfig
      command: |
        kubectl config set-context default \
        --cluster=kubernetes-the-hard-way \
        --user=system:node:worker-{{ item }} \
        --kubeconfig=worker-{{ item }}.kubeconfig
      args:
        chdir: files

    - name: Set worker-{{ item }} use context in kubeconfig
      command: kubectl config use-context default --kubeconfig=worker-{{ item }}.kubeconfig
      args:
        chdir: files
  when: worker_kubeconfig.stat.exists == false
