---

# https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control
# Prerequisites for using Role-Based Access Control

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gcpaleksandrloktionov1@gmail.com
