---
groups:
  - name: alert.rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: page
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
          summary: 'Instance {{ $labels.instance }} down'
      - alert: UIHTTPHighResponceLatency
        expr: histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) > 0.5
        for: 1m
        labels:
          severity: page
        annotations:
          description: 'High response latency on {{ $labels.instance }}'
          summary: '{{ $labels.instance }} has a 95th percentile response latency above 0.5s (current value: {{ $value }}s)'
