---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: gitlab-runner-xenial64
    box: ubuntu/xenial64
provisioner:
  name: ansible
  inventory:
    host_vars:
      gitlab-runner-xenial64:
        docker_host_user: vagrant
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
