---
# defaults file for reddit_monolith

reddit_monolith_credentials: ~/.ansible/reddit_monolith_credentials.yml
reddit_monolith_docker_registry_user: "{{ mandatory }}"
reddit_monolith_docker_version: latest

reddit_monolith_docker_image: "{{ reddit_monolith_docker_registry_user }}/reddit:{{ reddit_monolith_docker_version }}"
reddit_monolith_app_port: 9292
reddit_monolit_db_port: 27017

reddit_monolith_docker_compose:
  version: '3'
  services:
    post_db:
      image: mongo:3.2
      volumes:
        - post_db:/data/db
      networks:
        - back_net
    reddit:
      image: "{{ reddit_monolith_docker_image }}"
      restart: always
      ports:
        - "{{ reddit_monolith_app_port }}:{{ reddit_monolith_app_port }}/tcp"
      networks:
        - back_net
        - front_net
      environment:
        DATABASE_URL: 'post_db:{{ reddit_monolit_db_port }}'
  volumes:
    post_db:
  networks:
    back_net:
    front_net:
