---
# defaults file for gitlab

gitlab_runner_credentials: ~/.ansible/gilab_runner_credentials.yml
gitlab_runner_dir: /srv/gitlab-runner
gitlab_runner_config_dir: "{{ gitlab_runner_dir }}/config"

# Usually gitlab_runner_coordinator_url and gitlab_runner_token
# should be loaded from gilab_runner_credentials.yml
# file during role execution
gitlab_runner_coordinator_url: "{{ mandatory }}"
gitlab_runner_token: "{{ mandatory }}"
gitlab_runner_name: my-runner
gitlab_runner_tags:
  - linux
  - xenial
  - ubuntu
  - docker

gitlab_runner_run_untagged: true
gitlab_runner_locked: false
gitlab_runner_executor: docker
gitlab_runner_docker_image: alpine:latest

gitlab_runner_docker_compose:
  version: '3'
  services:
    runner:
      image: 'gitlab/gitlab-runner:latest'
      restart: always
      volumes:
        - '{{ gitlab_runner_config_dir }}:/etc/gitlab-runner'
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        - REGISTRATION_TOKEN={{ gitlab_runner_token }}
        - CI_SERVER_URL={{ gitlab_runner_coordinator_url }}
        - RUNNER_EXECUTOR={{ gitlab_runner_executor }}
        - RUNNER_TAG_LIST={{ gitlab_runner_tags | join(",") }}
        - DOCKER_IMAGE={{ gitlab_runner_docker_image }}
        - RUNNER_NAME={{ gitlab_runner_name }}
        - REGISTER_NON_INTERACTIVE=true
        - REGISTER_LOCKED={{ gitlab_runner_locked }}
        - REGISTER_RUN_UNTAGGED={{ gitlab_runner_run_untagged }}
