---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: gitlab-omnibus-xenial64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 18080"
    box: ubuntu/xenial64
    memory: 4096
    cpus: 2
provisioner:
  name: ansible
  inventory:
    host_vars:
      gitlab-omnibus-xenial64:
        docker_host_user: vagrant
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
