---
# defaults file for autoheal

env: local

autoheal_prerequisite_packages:
  - make

autoheal_python_modules:
  - { module: docker, version: 3.4.1 }

autoheal_repo_version: monitoring-2
autoheal_image_version: 4.0.0-0.9.0
autoheal_credentials: ~/.ansible/autoheal_credentials.yml

autoheal_awx_address: http://localhost/api
autoheal_awx_username: "{{ mandatory }}"
autoheal_awx_password: "{{ mandatory }}"

autoheal_config:
  awx:
    address: "{{ autoheal_awx_address }}"
    credentials:
      username: "{{ autoheal_awx_username }}"
      password: "{{ autoheal_awx_password }}"
    project: otus
  rules:
    - metadata:
        name: start-services
      labels:
        alertname: ".*InstanceDown.*"
      awxJob:
        template: "run_microservices"
